---
- name: mail
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Send mail
      mail:
        host: 
        port: 25
        username: 
        password: 
        subject: Mail test in progress
        body: Mail on fire
        from: 
        to: 
#        secure: always
      delegate_to: localhost
      run_once: True
      
        
